<?php

$title = 'Delete post';
$url   = $this->url('post', ['action' => 'delete', 'id' => $this->postId]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?php if ($this->isLoggedIn && $this->userId == $this->postUserId): ?>
<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($this->post->getTitle()) ?>" by
    "<?= $this->escapeHtml($this->post->user->getUsername()) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $this->post->getId() ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>

<?php else:?>
    <h1>You can't edit Post</h1>
<?php endif; ?>
