<?php

$title = 'Delete post';
$url   = $this->url('post', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($this->post->getTitle()) ?>" by
    "<?= $this->escapeHtml($this->post->getDescription()) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $post->getId() ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>