<?php if ($this->user): ?>
    <h3><?php echo $this->user->getUsername(); ?> logined!</h3>
<?php else: ?>
    <p>No user logged in.</p>
<?php endif; ?>
<?php
$title = 'My posts';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('post', ['action' => 'add']) ?>">Add new post</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Created Time</th>
        <th>Author</th>
        <th>Image</th>
        <th>&nbsp;</th>
    </tr>


    <?php foreach ($this->paginator as $post) : ?>
        <tr>
            <td>
                    <?= $this->escapeHtml($post->getTitle());?>
            </td>
            <td>

                <?=$this->escapeHtml($post->getDescription()); ?>
            </td>

            <td>
                <?=$this->escapeHtml($post->getCreatedAt());?>
            </td>
            <td>
                <?= $this->escapeHtml($post->user->getUsername());?>
            </td>
            <td>
                <?php if (!empty($post->getImage())) : ?>
                    <img src="<?= $this->escapeHtmlAttr($this->basePath(substr($post->getImage(), 8))) ?>" alt="<?= $this->escapeHtmlAttr($post->getTitle()) ?>" width="100">
                <?php endif; ?>
            </td>
            <?php if ($this->user->getId() == $post->user->getId()) : ?>
            <td>
                <a href="<?= $this->url('post', ['action' => 'edit', 'id' => $post->getId()]) ?>">Edit</a>
                <a href="<?= $this->url('post', ['action' => 'delete', 'id' => $post->getId()]) ?>">Delete</a>
            </td>
            <?php else : ?>
            <td>Can't Change </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>

</table>



<?= $this->partial('partial/paginator', ['paginator' => $this->paginator]); ?>

