
<?php if (isset($paginator) && $paginator->count() > 1) : ?>
    <div class="pagination-container">
        <div class="pagination">
            <?php if ($this->paginator->getPages()->current > 1) : ?>
                <a href="<?= $this->url(null, [], ['query' => ['page' => $this->paginator->getPages()->current - 1]]) ?>" class="pagination-link">Previous</a>
            <?php endif; ?>

            <?php foreach ($this->paginator->getPages()->pagesInRange as $page) : ?>
                <?php if ($page == $this->paginator->getPages()->current) : ?>
                    <span class="pagination-current"><?= $page ?></span>
                <?php else : ?>
                    <a href="<?= $this->url(null, [], ['query' => ['page' => $page]]) ?>" class="pagination-link"><?= $page ?></a>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if ($this->paginator->getPages()->current < $this->paginator->getPages()->last) : ?>
                <a href="<?= $this->url(null, [], ['query' => ['page' => $this->paginator->getPages()->current + 1]]) ?>" class="pagination-link">Next</a>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
